name: Publish Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install atm dependencies
        working-directory: ./atm
        run: |
          npm ci
          npm install @compodoc/compodoc@1.1.19 --save-dev

      - name: Install payment dependencies
        working-directory: ./payment
        run: |
          npm ci
          npm install @compodoc/compodoc@1.1.19 --save-dev

      - name: Generate atm documentation
        working-directory: ./atm
        run: npx @compodoc/compodoc -p tsconfig.json -d documentation --hideGenerator

      - name: Generate payment documentation
        working-directory: ./payment
        run: npx @compodoc/compodoc -p tsconfig.json -d documentation --hideGenerator

      - name: Create combined documentation structure
        run: |
          mkdir -p ./combined-docs
          cp -r ./atm/documentation/* ./combined-docs/
          mkdir -p ./combined-docs/payment
          cp -r ./payment/documentation/* ./combined-docs/payment/

      - name: Create index page for combined docs
        run: |
          cat > ./combined-docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Combined Documentation</title>
              <link rel="stylesheet" href="styles.css">
          </head>
          <body>
              <header>
                  <h1>Combined Documentation</h1>
                  <nav>
                      <ul>
                          <li><a href="#atm-docs">ATM Documentation</a></li>
                          <li><a href="#payment-docs">Payment Documentation</a></li>
                      </ul>
                  </nav>
              </header>
              <main>
                  <section id="atm-docs">
                      <h2>ATM Documentation</h2>
                      <div id="atm-docs-content"></div>
                  </section>
                  <section id="payment-docs">
                      <h2>Payment Documentation</h2>
                      <div id="payment-docs-content"></div>
                  </section>
              </main>
              <footer>
                  <p>Combined documentation generated by Compodoc</p>
              </footer>
              <script>
                  function loadDocs(section, path) {
                      fetch(path)
                          .then(response => response.text())
                          .then(data => {
                              document.getElementById(section).innerHTML = data;
                          })
                          .catch(error => console.error('Error loading documentation:', error));
                  }

                  loadDocs('atm-docs-content', 'atm/documentation/index.html');
                  loadDocs('payment-docs-content', 'payment/documentation/index.html');
              </script>
          </body>
          </html>
          EOF

      - name: Move combined documentation to final location
        run: |
          mv ./combined-docs ./documentation

      - name: Add .nojekyll file
        run: touch ./documentation/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './documentation'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4